language: node_js
sudo: true
node_js:
  - "4"
  - "6"
dist: trusty
before_install: if [[ `npm -v` < 3 ]]; then npm i -g npm@4; fi
before_script:
  - npm install -g grunt-cli
  - chmod 777 ./setup/redis/travis-redis.sh
  - ./setup/redis/travis-redis.sh
  - grunt css
addons: 
  apt:
    packages:
      - google-chrome-stable
services:
  - redis-server
notifications:
    flowdock: 7d2ea551a0757bea5b52c496f3a7ab2e
