language: node_js
sudo: true
node_js:
  - "8"
dist: trusty
before_script:
  - npm install -g grunt-cli
  - chmod 777 ./setup/travis/travis-redis.sh
  - ./setup/travis/travis-redis.sh
  - grunt css
addons: 
  apt:
    packages:
      - google-chrome-stable
services:
  - redis-server
notifications:
    flowdock: 7d2ea551a0757bea5b52c496f3a7ab2e
