language: node_js
sudo: true
node_js:
  - "0.10"
  - "0.12"
  - "4"
dist: trusty
before_script:
  - npm install -g grunt-cli
  - cp ./config/default-config.json ./config/config.json
  - chmod 777 ./setup/redis/travis-redis.sh
  - ./setup/redis/travis-redis.sh
  - grunt sass
services:
  - redis-server
notifications:
    flowdock: 7d2ea551a0757bea5b52c496f3a7ab2e
